# Generated by Django 2.0.6 on 2018-06-03 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20180603_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='date_subscribed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='subscribed'),
        ),
    ]
