# Generated by Django 2.0.6 on 2018-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='date_updated',
            new_name='update_date',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='date_subscribed',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='confirm_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirm date'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='optin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='opt-in date'),
        ),
    ]
