# Generated by Django 2.0.6 on 2018-06-05 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20180605_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='optin_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='opt-in date'),
        ),
    ]
