# Generated by Django 2.0.6 on 2018-06-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
