# Generated by Django 2.0.6 on 2018-06-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_auto_20180607_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='campaigns.Email'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='campaigns.Link'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='subscribers.Subscriber'),
        ),
    ]
