# Generated by Django 2.0.6 on 2018-06-08 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0008_activity_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='confirm IP address'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_seen_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last seen date'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='last_seen_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='last seen IP address'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated'),
        ),
    ]
