# Generated by Django 2.0.6 on 2018-06-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20180613_1254'),
        ('subscribers', '0009_auto_20180608_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.PositiveSmallIntegerField(choices=[(1, 'Subscribe page'), (2, 'Subscribe thank you page'), (3, 'Opt-in confirm email'), (4, 'Opt-in confirm thank you page'), (5, 'Final welcome email'), (6, 'Unsubscribe page'), (7, 'Unsubscribe success page'), (8, 'Goodbye email')], verbose_name='key')),
                ('template_type', models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'Page')], verbose_name='type')),
                ('workflow', models.PositiveSmallIntegerField(choices=[(1, 'Subscription'), (2, 'Unsubscription')], verbose_name='workflow')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('redirect_url', models.URLField(blank=True, verbose_name='redirect URL')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('content_html', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_templates', to='lists.MailingList', verbose_name='mailing list')),
            ],
            options={
                'verbose_name': 'form template',
                'verbose_name_plural': 'forms templates',
            },
        ),
    ]
