# Generated by Django 2.0.6 on 2018-06-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_formtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='key',
            field=models.CharField(choices=[('subscribe', 'Subscribe page'), ('subscribe_thank_you', 'Subscribe thank you page'), ('confirm_email', 'Opt-in confirm email'), ('confirm_thank_you', 'Opt-in confirm thank you page'), ('welcome_email', 'Final welcome email'), ('unsubscribe', 'Unsubscribe page'), ('unsubscribe_success', 'Unsubscribe success page'), ('goodbye_email', 'Goodbye email')], db_index=True, max_length=30, verbose_name='key'),
        ),
    ]
