# Generated by Django 2.0.6 on 2018-06-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0012_auto_20180614_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Subscribed'), (2, 'Unsubscribed'), (3, 'Was sent'), (4, 'Opened'), (5, 'Clicked')], default=1, verbose_name='type'),
            preserve_default=False,
        ),
    ]
