# Generated by Django 2.0.6 on 2018-06-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='mailing_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='mailing.MailingList'),
            preserve_default=False,
        ),
    ]
