# Generated by Django 2.0.6 on 2018-06-04 18:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20180604_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('content', models.TextField(blank=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'subscription form template',
                'verbose_name_plural': 'subscription form templates',
            },
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionformtemplate',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_form_templates', to='mailing.MailingList', verbose_name='mailing list'),
        ),
    ]
