# Generated by Django 2.0.6 on 2018-06-14 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('content', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
            },
        ),
    ]
