# Generated by Django 2.0.6 on 2018-06-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='last_used_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last used'),
        ),
    ]
