# Generated by Django 2.1 on 2018-08-12 20:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('campaign_type', models.PositiveSmallIntegerField(choices=[(1, 'Regular'), (2, 'Automated'), (3, 'A/B Test')], default=1, verbose_name='type')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Sent'), (2, 'Scheduled'), (3, 'Draft'), (4, 'Queued'), (5, 'Delivering'), (6, 'Paused')], db_index=True, default=3, verbose_name='status')),
                ('send_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='send date')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update date')),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('track_opens', models.BooleanField(default=True, verbose_name='track opens')),
                ('track_clicks', models.BooleanField(default=True, verbose_name='track clicks')),
                ('unique_opens_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='unique opens')),
                ('total_opens_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='total opens')),
                ('unique_clicks_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='unique clicks')),
                ('total_clicks_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='total clicks')),
                ('open_rate', models.FloatField(default=0.0, editable=False, verbose_name='opens')),
                ('click_rate', models.FloatField(default=0.0, editable=False, verbose_name='clicks')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'db_table': 'colossus_campaigns',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('template_content', models.TextField(blank=True, verbose_name='email template content')),
                ('from_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('from_name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('subject', models.CharField(max_length=150, verbose_name='subject')),
                ('preview', models.CharField(blank=True, max_length=150, verbose_name='preview')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('content_html', models.TextField(blank=True, verbose_name='content HTML')),
                ('content_text', models.TextField(blank=True, verbose_name='content plain text')),
                ('unique_opens_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='unique opens')),
                ('total_opens_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='total opens')),
                ('unique_clicks_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='unique clicks')),
                ('total_clicks_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='total clicks')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='campaigns.Campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
                'db_table': 'colossus_emails',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField(max_length=2048, verbose_name='URL')),
                ('unique_clicks_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='unique clicks count')),
                ('total_clicks_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='total clicks count')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='index')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='campaigns.Email', verbose_name='email')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'db_table': 'colossus_links',
            },
        ),
    ]
