# Generated by Django 2.0.6 on 2018-06-14 08:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('campaign_type', models.PositiveSmallIntegerField(choices=[(1, 'Regular'), (2, 'Automated'), (3, 'A/B Test')], default=1, verbose_name='type')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Sent'), (2, 'Scheduled'), (3, 'Draft'), (4, 'Trashed')], default=3, verbose_name='status')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='send date')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update date')),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('track_opens', models.BooleanField(default=True, verbose_name='track opens')),
                ('track_clicks', models.BooleanField(default=True, verbose_name='track clicks')),
                ('unique_opens_count', models.PositiveIntegerField(default=0)),
                ('unique_clicks_count', models.PositiveIntegerField(default=0)),
                ('total_opens_count', models.PositiveIntegerField(default=0)),
                ('total_clicks_count', models.PositiveIntegerField(default=0)),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='lists.MailingList', verbose_name='mailing list')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('from_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('from_name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('subject', models.CharField(max_length=150, verbose_name='subject')),
                ('preview', models.CharField(blank=True, max_length=150, verbose_name='preview')),
                ('content', models.TextField(verbose_name='content')),
                ('content_text', models.TextField(verbose_name='content')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='campaigns.Campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField(max_length=2048)),
                ('unique_clicks_count', models.PositiveIntegerField(default=0)),
                ('total_clicks_count', models.PositiveIntegerField(default=0)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Email')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
        ),
    ]
