# Generated by Django 2.0.7 on 2018-07-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20180721_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sent'), (2, 'Scheduled'), (3, 'Draft'), (4, 'Queued'), (5, 'Delivering'), (6, 'Paused')], db_index=True, default=3, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='link',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='campaigns.Email'),
        ),
    ]
