# Generated by Django 2.0.6 on 2018-06-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_email_content_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='content_blocks',
        ),
        migrations.AddField(
            model_name='email',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='content HTML'),
        ),
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='email',
            name='content_text',
            field=models.TextField(blank=True, verbose_name='content plain text'),
        ),
    ]
