# Generated by Django 2.0.7 on 2018-07-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20180722_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='campaigns.Email', verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='link',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='link',
            name='total_clicks_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='total clicks count'),
        ),
        migrations.AlterField(
            model_name='link',
            name='unique_clicks_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='unique clicks count'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=2048, verbose_name='URL'),
        ),
    ]
