# Generated by Django 2.1.5 on 2019-01-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_auto_20180825_0042'),
        ('campaigns', '0003_auto_20180815_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='subscribers.Tag', verbose_name='tag'),
        ),
    ]
