# Generated by Django 2.0.6 on 2018-06-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20180622_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='send_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='send date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sent'), (2, 'Scheduled'), (3, 'Draft'), (4, 'Trashed')], db_index=True, default=3, verbose_name='status'),
        ),
    ]
