# Generated by Django 2.0.7 on 2018-07-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20180630_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='total_clicks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='total clicks'),
        ),
        migrations.AddField(
            model_name='email',
            name='total_opens_count',
            field=models.PositiveIntegerField(default=0, verbose_name='total opens'),
        ),
        migrations.AddField(
            model_name='email',
            name='unique_clicks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='unique clicks'),
        ),
        migrations.AddField(
            model_name='email',
            name='unique_opens_count',
            field=models.PositiveIntegerField(default=0, verbose_name='unique opens'),
        ),
    ]
