# Generated by Django 2.0.7 on 2018-07-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_auto_20180710_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='total_clicks_count',
        ),
        migrations.RemoveField(
            model_name='email',
            name='unique_clicks_count',
        ),
    ]
