# Generated by Django 2.0.7 on 2018-07-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20180710_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='click_rate',
            field=models.FloatField(default=0.0, editable=False, verbose_name='click rate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='open_rate',
            field=models.FloatField(default=0.0, editable=False, verbose_name='open rate'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_clicks_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='total clicks'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_opens_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='total opens'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='unique_clicks_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='unique clicks'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='unique_opens_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='unique opens'),
        ),
    ]
