# Generated by Django 2.0.7 on 2018-07-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_auto_20180717_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='click_rate',
            field=models.FloatField(default=0.0, editable=False, verbose_name='clicks'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='open_rate',
            field=models.FloatField(default=0.0, editable=False, verbose_name='opens'),
        ),
        migrations.AddField(
            model_name='email',
            name='total_clicks_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='total clicks'),
        ),
        migrations.AddField(
            model_name='email',
            name='unique_clicks_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='unique clicks'),
        ),
        migrations.AlterField(
            model_name='email',
            name='total_opens_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='total opens'),
        ),
        migrations.AlterField(
            model_name='email',
            name='unique_opens_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='unique opens'),
        ),
        migrations.AlterField(
            model_name='link',
            name='total_clicks_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='unique_clicks_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
