# Generated by Django 2.0.6 on 2018-06-14 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('subscribers_count', models.PositiveIntegerField(default=0, verbose_name='subscribers')),
                ('open_rate', models.FloatField(default=0.0, verbose_name='opens')),
                ('click_rate', models.FloatField(default=0.0, verbose_name='clicks')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('contact_email_address', models.EmailField(blank=True, max_length=254, verbose_name='contact email address')),
                ('website_url', models.URLField(blank=True, help_text='Where did people opt in to this list?', verbose_name='website URL')),
                ('campaign_default_from_name', models.CharField(blank=True, max_length=100, verbose_name='default from name')),
                ('campaign_default_from_email', models.EmailField(blank=True, max_length=254, verbose_name='default from email address')),
                ('campaign_default_email_subject', models.CharField(blank=True, max_length=150, verbose_name='default subject')),
                ('enable_recaptcha', models.BooleanField(default=False, verbose_name='enable reCAPTCHA')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'db_table': 'mailing_lists',
            },
        ),
    ]
