# Generated by Django 2.1.3 on 2018-11-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='recaptcha_secret_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='secret key'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='recaptcha_site_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='site key'),
        ),
    ]
