# Generated by Django 2.0.6 on 2018-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='forms_custom_css',
            field=models.TextField(blank=True, verbose_name='custom CSS'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='forms_custom_header',
            field=models.TextField(blank=True, verbose_name='custom header'),
        ),
    ]
