# Generated by Django 2.0.7 on 2018-07-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberimport',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='size'),
        ),
    ]
