# Generated by Django 2.0.6 on 2018-06-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20180618_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='forms_custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS will be applied to all subscription form pages.', verbose_name='custom CSS'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='forms_custom_header',
            field=models.TextField(blank=True, help_text='Header displayed on all subscription form pages. Accepts HTML. If empty, the name of the mailing list will be used.', verbose_name='custom header'),
        ),
    ]
