# Generated by Django 2.0.7 on 2018-07-29 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_subscriberimport_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberimport',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers_imports', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='subscriberimport',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers_imports', to='lists.MailingList', verbose_name='mailing list'),
        ),
    ]
