# Generated by Django 2.0.6 on 2018-06-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20180619_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='forms_custom_header',
            field=models.TextField(blank=True, help_text='Header displayed on all subscription form pages. Accepts HTML.\n                       If empty, the name of the mailing list will be used.', verbose_name='custom header'),
        ),
    ]
