# Generated by Django 2.0.6 on 2018-06-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180624_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200, verbose_name='host'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='port'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='smtp_ssl_certfile',
            field=models.TextField(blank=True, verbose_name='SSL certfile'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='smtp_ssl_keyfile',
            field=models.TextField(blank=True, verbose_name='SSL keyfile'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='smtp_timeout',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='timeout'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, verbose_name='use SSL'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='use TLS'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=200, verbose_name='username'),
        ),
    ]
