# Generated by Django 2.1 on 2018-08-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20180805_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberimport',
            name='import_type',
        ),
        migrations.AlterField(
            model_name='subscriberimport',
            name='subscriber_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Subscribed'), (3, 'Unsubscribed'), (4, 'Cleaned')], default=2, verbose_name='assign status to subscriber'),
        ),
        migrations.AlterField(
            model_name='subscriberimport',
            name='update_or_create',
            field=models.BooleanField(default=True, help_text='If the email address is already subscribed to the list, the entry will be updated with data from the CSV file. If this option is left unchecked, only new email addresses will be created.', verbose_name='update or create subscriber'),
        ),
    ]
