# Generated by Django 2.1 on 2018-08-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_subscriberimport_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberimport',
            name='update_or_create',
        ),
        migrations.AlterField(
            model_name='subscriberimport',
            name='strategy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Create new subscribers only'), (2, 'Update existing subscribers only'), (3, 'Update or create subscribers')], default=3, help_text='The email address will be used as the main subscriber identifier to determine if they are already on the list.', verbose_name='import strategy'),
        ),
    ]
