# Generated by Django 2.0.6 on 2018-06-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_mailinglist_email_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='email_manager',
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='list_manager',
            field=models.EmailField(blank=True, help_text='Email address to handle subscribe/unsubscribe requests.\n                       It can be a real email address or an automated route to handle callbacks/webhooks.', max_length=254, verbose_name='list manager'),
        ),
    ]
