# Generated by Django 2.0.6 on 2018-07-01 16:32

import colossus.apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_auto_20180630_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('file', models.FileField(storage=colossus.apps.core.storage.PrivateMediaStorage(), upload_to='uploads', verbose_name='CSV file')),
                ('columns_mapping', models.TextField(blank=True, verbose_name='columns mapping')),
                ('subscriber_status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Subscribed'), (3, 'Unsubscribed'), (4, 'Cleaned')], default=2, verbose_name='subscriber status')),
            ],
            options={
                'verbose_name': 'subscribers import',
                'verbose_name_plural': 'subscribers imports',
                'db_table': 'subscribers_imports',
            },
        ),
    ]
