# Generated by Django 2.0.6 on 2018-07-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_subscriberimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberimport',
            name='mailing_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lists.MailingList'),
            preserve_default=False,
        ),
    ]
