# Generated by Django 2.0.7 on 2018-07-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_subscriberimport_mailing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberimport',
            name='import_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Advanced')], default=1, verbose_name='import type'),
        ),
        migrations.AddField(
            model_name='subscriberimport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Errored'), (4, 'Canceled')], default=1, verbose_name='status'),
        ),
    ]
