# Generated by Django 2.0.6 on 2018-06-06 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20180605_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.CharField(max_length=150, verbose_name='from')),
                ('subject', models.CharField(max_length=150, verbose_name='subject')),
                ('preview', models.CharField(max_length=300, verbose_name='preview')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='send date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Regular'), (2, 'Automated'), (3, 'A/B Test')], default=1, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='email',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='campaigns.Campaign', verbose_name='campaign'),
        ),
    ]
