# Generated by Django 2.0.6 on 2018-06-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20180606_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email_from',
        ),
        migrations.AddField(
            model_name='email',
            name='from_email',
            field=models.EmailField(default='', max_length=254, verbose_name='from email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='from_name',
            field=models.CharField(default='', max_length=100, verbose_name='from name'),
            preserve_default=False,
        ),
    ]
