# Generated by Django 2.0.6 on 2018-06-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_auto_20180606_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='from name'),
        ),
    ]
