# Generated by Django 2.0.6 on 2018-06-06 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20180606_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField(max_length=2048)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Email')),
            ],
        ),
    ]
