# Generated by Django 2.0.6 on 2018-06-07 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20180606_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
