# Generated by Django 2.0.6 on 2018-06-08 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaign_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='update date'),
        ),
    ]
