# Generated by Django 2.0.6 on 2018-06-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_auto_20180608_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='track_clicks',
            field=models.BooleanField(default=True, verbose_name='track clicks'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='track_opens',
            field=models.BooleanField(default=True, verbose_name='track opens'),
        ),
    ]
