# Generated by Django 2.0.6 on 2018-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_auto_20180609_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='click_count',
            new_name='total_clicks_count',
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_opens_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='unique_clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
