# Generated by Django 2.0.6 on 2018-06-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_auto_20180609_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
