# Generated by Django 2.1 on 2018-08-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Subscribers import completed'), (2, 'Subscribers import failed'), (3, 'Campaign sent'), (4, 'List cleaned')], verbose_name='action'),
        ),
    ]
