# Generated by Django 2.0.6 on 2018-06-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='template_type',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='workflow',
        ),
    ]
