# Generated by Django 2.1 on 2018-08-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last campaign sent date'),
        ),
    ]
