# Generated by Django 2.0.6 on 2018-06-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('subscribers', '0002_auto_20180614_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('subscribe', 'Subscribe page'), ('subscribe-thank-you', 'Subscribe thank you page'), ('confirm-email', 'Opt-in confirm email'), ('confirm-thank-you', 'Opt-in confirm thank you page'), ('welcome-email', 'Final welcome email'), ('unsubscribe', 'Unsubscribe page'), ('unsubscribe-success', 'Unsubscribe success page'), ('goodbye-email', 'Goodbye email')], db_index=True, max_length=30, verbose_name='key')),
                ('redirect_url', models.URLField(blank=True, verbose_name='redirect URL')),
                ('send_email', models.BooleanField(default=True, verbose_name='send final confirmation email?')),
                ('from_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('from_name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('subject', models.CharField(blank=True, max_length=150, verbose_name='subject')),
                ('content_html', models.TextField(blank=True, verbose_name='content HTML')),
                ('content_text', models.TextField(blank=True, verbose_name='content plain text')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_templates', to='lists.MailingList', verbose_name='mailing list')),
            ],
            options={
                'verbose_name': 'form template',
                'verbose_name_plural': 'form templates',
            },
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='mailing_list',
        ),
        migrations.DeleteModel(
            name='FormTemplate',
        ),
    ]
