# Generated by Django 2.1 on 2018-08-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20180815_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionformtemplate',
            name='key',
            field=models.CharField(choices=[('subscribe', 'Subscribe form'), ('subscribe-thank-you', 'Subscribe thank you page'), ('confirm-email', 'Opt-in confirm email'), ('confirm-thank-you', 'Opt-in confirm thank you page'), ('welcome-email', 'Final welcome email'), ('unsubscribe', 'Unsubscribe form'), ('unsubscribe-success', 'Unsubscribe success page'), ('goodbye-email', 'Goodbye email')], db_index=True, max_length=30, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='subscriptionformtemplate',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='email subject'),
        ),
    ]
