# Generated by Django 2.0.6 on 2018-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20180615_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionformtemplate',
            name='from_email',
            field=models.EmailField(max_length=254, verbose_name='from email address'),
        ),
        migrations.AlterField(
            model_name='subscriptionformtemplate',
            name='from_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='from name'),
        ),
        migrations.AlterField(
            model_name='subscriptionformtemplate',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='Instead of showing this page, redirect to URL.', verbose_name='redirect URL'),
        ),
        migrations.AlterField(
            model_name='subscriptionformtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=150, verbose_name='email subject'),
        ),
    ]
