# Generated by Django 2.0.7 on 2018-07-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_auto_20180618_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='click_rate',
            field=models.FloatField(default=0.0, editable=False, verbose_name='clicks'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='open_rate',
            field=models.FloatField(default=0.0, editable=False, verbose_name='opens'),
        ),
    ]
