# Generated by Django 2.1 on 2018-08-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_auto_20180816_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionformtemplate',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='send final confirmation email?'),
        ),
    ]
