# Generated by Django 2.1 on 2018-08-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0009_auto_20180823_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='subscribers.Tag', verbose_name='tags'),
        ),
    ]
