# Generated by Django 2.0.6 on 2018-06-05 16:47

import colossus.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=colossus.core.models.default_token, editable=False, max_length=50, unique=True)),
                ('description', models.CharField(db_index=True, max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('expires', models.IntegerField(default=7)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'tokens',
            },
        ),
    ]
