# Generated by Django 2.0.6 on 2018-06-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
