# Generated by Django 2.0.6 on 2018-06-02 16:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('campaign_type', models.PositiveSmallIntegerField(choices=[(1, 'Regular'), (2, 'Automated')], default=1, verbose_name='type')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('subscribers_count', models.PositiveIntegerField(default=0, verbose_name='subscribers')),
                ('open_rate', models.FloatField(default=0.0, verbose_name='opens')),
                ('click_rate', models.FloatField(default=0.0, verbose_name='clicks')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'db_table': 'mailing_lists',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='name')),
                ('open_rate', models.FloatField(default=0.0, verbose_name='opens')),
                ('click_rate', models.FloatField(default=0.0, verbose_name='clicks')),
                ('date_subscribed', models.DateTimeField(auto_now_add=True, verbose_name='subscribed')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Subscribed'), (3, 'Unsubscribed'), (4, 'Cleaned')], default=1, verbose_name='status')),
                ('optin_ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='opt-in IP address')),
                ('confirm_ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='confirm IP address')),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
            },
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='subscribers',
            field=models.ManyToManyField(to='mailing.Subscriber'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='mailing.MailingList', verbose_name='mailing list'),
        ),
    ]
