# Generated by Django 2.0.6 on 2018-06-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_form_templates', to='lists.MailingList', verbose_name='mailing list')),
            ],
            options={
                'verbose_name': 'subscription form template',
                'verbose_name_plural': 'subscription form templates',
            },
        ),
    ]
