# Generated by Django 2.0.6 on 2018-06-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_subscriptionformtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='slug',
            field=models.SlugField(default='newsletter', max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
