# Generated by Django 2.0.6 on 2018-06-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_auto_20180603_1558'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriber',
            unique_together={('email', 'mailing_list')},
        ),
    ]
