# Generated by Django 2.0.6 on 2018-06-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_mailinglist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='campaign_default_email_subject',
            field=models.CharField(blank=True, max_length=150, verbose_name='default subject'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='campaign_default_from_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='default from email address'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='campaign_default_from_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='default from name'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='enable_recaptcha',
            field=models.BooleanField(default=False, verbose_name='enable reCAPTCHA'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='website_url',
            field=models.URLField(blank=True, help_text='Where did people opt in to this list?', verbose_name='website URL'),
        ),
    ]
