# Generated by Django 2.0.6 on 2018-06-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_mailinglist_contact_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionformtemplate',
            name='mailing_list',
        ),
        migrations.DeleteModel(
            name='SubscriptionFormTemplate',
        ),
    ]
