# Generated by Django 2.0.6 on 2018-06-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_auto_20180604_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='mailing_list',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
